version: '2.1'

services:

  loja:
    build: .
    container_name: loja
    ports:
      - "8181:8181"
    depends_on:
        db:
            condition: service_healthy
    links:
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --sql_mode="" --lower_case_table_names=1

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=loja
    ports:
      - "3306:3306"
      
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-proot", "ping", "-h" ,"localhost"]
        timeout: 20s
        retries: 10
         
        
        